/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aroulette;

import javax.swing.JFileChooser;


/**
 *
 * @author aitatxoborja
 */
public class ConfigWindow extends javax.swing.JFrame {

    private ConfigurationManager _config;
    
    /**
     * Creates new form ConfigWindow
     */
    public ConfigWindow(ConfigurationManager config) {
        
        _config = config;
        initComponents();     
        updateInterface();
    }
    
    private void updateInterface ()
    {
        jTextFieldCurrentDir.setText(_config.getDefaultDir());
        jTextFieldExponent.setText(""+_config.getExponent());
        jSliderImpulse.setValue((int)_config.getImpulse());
        jSliderResistance.setValue((int)_config.getResistance());
        jLabelEstimationValues.setText(_config.getRunTimeInterval());
        jComboBoxAppearence.setSelectedItem(_config.getAppearance());
        jComboBoxLanguage.setSelectedItem(_config.getLanguages());
    }

    private void updateConfigFile ()
    {
        _config.setAppearance((String)jComboBoxAppearence.getSelectedItem());
        _config.setLocale((String)jComboBoxLanguage.getSelectedItem());
        _config.setDefaultDir(jTextFieldCurrentDir.getText());
        _config.setExponent(Double.parseDouble(jTextFieldExponent.getText()));
        _config.setImpulse(jSliderImpulse.getValue());
        _config.setResistance(jSliderResistance.getValue());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1Roulette = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelLanguage = new javax.swing.JLabel();
        jComboBoxLanguage = new javax.swing.JComboBox();
        jLabelLanguage1 = new javax.swing.JLabel();
        jComboBoxAppearence = new javax.swing.JComboBox();
        jLabelDir = new javax.swing.JLabel();
        jTextFieldCurrentDir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabeExponent = new javax.swing.JLabel();
        jSliderImpulse = new javax.swing.JSlider();
        jTextFieldExponent = new javax.swing.JTextField();
        jLabelImpulse = new javax.swing.JLabel();
        jLabelResistance = new javax.swing.JLabel();
        jSliderResistance = new javax.swing.JSlider();
        jLabelEstimation = new javax.swing.JLabel();
        jLabelEstimationValues = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("aroulette/resources/Bundle"); // NOI18N
        setTitle(bundle.getString("AROULETTE CONFIGURATION")); // NOI18N
        setPreferredSize(new java.awt.Dimension(475, 375));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelLanguage.setText(bundle.getString("LANGUAGE")); // NOI18N

        jLabelLanguage1.setText(bundle.getString("APPEARENCE")); // NOI18N

        jLabelDir.setText(bundle.getString("DEFAULT DIRECTORY")); // NOI18N

        jTextFieldCurrentDir.setText("");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aroulette/resources/Folder Open.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLanguage1)
                            .addComponent(jLabelLanguage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxAppearence, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxLanguage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jTextFieldCurrentDir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLanguage)
                    .addComponent(jComboBoxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLanguage1)
                    .addComponent(jComboBoxAppearence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCurrentDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDir))))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        String [] languages = _config.getLanguages();
        jComboBoxLanguage.removeAllItems();
        int index = 0;
        String current=_config.getLocale();
        for (int s=0; s<languages.length; s++)
        {
            if (current.equals(languages[s])) index = s;
            jComboBoxLanguage.addItem(languages[s]);
        }
        jComboBoxLanguage.setSelectedIndex(index);
        String [] looks = _config.getLookAndFeelOptions();
        jComboBoxAppearence.removeAllItems();
        index = 0;
        current=_config.getAppearance();
        for (int s=0; s<looks.length; s++)
        {
            if (current.equals(looks[s])) index = s;
            jComboBoxAppearence.addItem(looks[s]);
        }
        jComboBoxAppearence.setSelectedIndex(index);
        jTextFieldCurrentDir.setText(_config.getDefaultDir());

        jTabbedPane1Roulette.addTab("Program", jPanel1);
        jTabbedPane1Roulette.addTab(bundle.getString("PROGRAM"), jPanel1);

        jLabeExponent.setText(bundle.getString("EXPONENT")); // NOI18N

        jSliderImpulse.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderImpulse.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderImpulseStateChanged(evt);
            }
        });

        jTextFieldExponent.setText("");

        jLabelImpulse.setText(bundle.getString("IMPULSE")); // NOI18N

        jLabelResistance.setText(bundle.getString("RESISTANCE")); // NOI18N

        jSliderResistance.setMinimum(1);
        jSliderResistance.setOrientation(javax.swing.JSlider.VERTICAL);
        jSliderResistance.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderResistanceStateChanged(evt);
            }
        });

        jLabelEstimation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstimation.setText(bundle.getString("RUN TIME ESTIMATION")); // NOI18N

        jLabelEstimationValues.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstimationValues.setText(java.util.ResourceBundle.getBundle("aroulette/resources/Bundle").getString("ESTIMATION"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeExponent)
                    .addComponent(jLabelImpulse)
                    .addComponent(jSliderImpulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResistance)
                    .addComponent(jSliderResistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldExponent, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEstimationValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEstimation, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeExponent)
                    .addComponent(jTextFieldExponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImpulse)
                    .addComponent(jLabelResistance)
                    .addComponent(jLabelEstimation))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSliderResistance, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addComponent(jSliderImpulse, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabelEstimationValues, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTextFieldExponent.setText(""+_config.getExponent());
        jLabelEstimationValues.setText(_config.getRunTimeInterval());

        jTabbedPane1Roulette.addTab("Roulette", jPanel4);
        jTabbedPane1Roulette.addTab(bundle.getString("ROULETTE"), jPanel4);

        jButtonOk.setText(bundle.getString("OK")); // NOI18N
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1Roulette)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1Roulette, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        this.updateConfigFile();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jSliderImpulseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderImpulseStateChanged
        
        _config.setAppearance((String)jComboBoxAppearence.getSelectedItem());
        _config.setLocale((String)jComboBoxLanguage.getSelectedItem());
        _config.setDefaultDir(jTextFieldCurrentDir.getText());
        _config.setExponent(Double.parseDouble(jTextFieldExponent.getText()));
        _config.setImpulse(jSliderImpulse.getValue());
        this.updateInterface();
    }//GEN-LAST:event_jSliderImpulseStateChanged

    private void jSliderResistanceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderResistanceStateChanged
        
        _config.setAppearance((String)jComboBoxAppearence.getSelectedItem());
        _config.setLocale((String)jComboBoxLanguage.getSelectedItem());
        _config.setDefaultDir(jTextFieldCurrentDir.getText());
        _config.setExponent(Double.parseDouble(jTextFieldExponent.getText()));
        _config.setResistance(jSliderResistance.getValue());
        this.updateInterface();
    }//GEN-LAST:event_jSliderResistanceStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.updateConfigFile();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int result;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File(_config.getDefaultDir()));
        chooser.setDialogTitle("Select default directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            _config.setDefaultDir(chooser.getSelectedFile().getPath());
            this.updateInterface();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBoxAppearence;
    private javax.swing.JComboBox jComboBoxLanguage;
    private javax.swing.JLabel jLabeExponent;
    private javax.swing.JLabel jLabelDir;
    private javax.swing.JLabel jLabelEstimation;
    private javax.swing.JLabel jLabelEstimationValues;
    private javax.swing.JLabel jLabelImpulse;
    private javax.swing.JLabel jLabelLanguage;
    private javax.swing.JLabel jLabelLanguage1;
    private javax.swing.JLabel jLabelResistance;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSliderImpulse;
    private javax.swing.JSlider jSliderResistance;
    private javax.swing.JTabbedPane jTabbedPane1Roulette;
    private javax.swing.JTextField jTextFieldCurrentDir;
    private javax.swing.JTextField jTextFieldExponent;
    // End of variables declaration//GEN-END:variables
}
